### ISSUE TITLE
E15090001

### ISSUE THREAD

**Issue by mikey0012** [SE23FT3/VMCS_CA#1]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash”

**Comment by luangxiao** [comment]
Assign to analyst to study the change item.

**Comment by adithya123** [comment]
Analysed the enhancement change requirements.

**Comment by luangxiao** [comment]
Approve the analysis document. Assigning tasks to developer.

**Comment by banijain** [comment]
Uploaded design document for E15090001. Ready for review.

**Comment by luangxiao** [comment]
Reviewed the design document. Implement E15090001.

**Comment by banijain** [comment]
Uploading codes, Ready for review.

**Comment by luangxiao** [comment]
Approved the code.Ready for testing.

**Comment by Zhangzhenzhen** [comment]
This issue can be closed.
