### ISSUE TITLE
D15090001

### ISSUE THREAD

**Issue by mikey0012** [SE23FT3/VMCS_CA#2]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash”.

**Comment by luangxiao** [comment]
Assign the defect to developer.

**Comment by banijain** [comment]
Uploaded the code. Ready for review.

**Comment by luangxiao** [comment]
Request for testing.

**Comment by yangchengvera** [comment]
Passed the testing for D15090001

**Comment by Zhangzhenzhen** [comment]
Request for a release.

**Comment by luangxiao** [comment]
Defect can be closed.
